const path = require('path');
const crypto = require('crypto');
const { write, exists, read, interpolate, resolveVar, toPosix, log } = require('./util');
const { renderDiagram } = require('./diagram');

const GENERATED_HEADER = '<!-- GENERATED by rensei-kata from rensei.graph.yaml — do not edit directly; edit .rensei/ and run `npx rensei-kata build` -->\n';

const MANIFEST_FILE = 'build-manifest.json';

// Protocol appended to every compiled agent that owns loop phases: the agents
// keep .rensei/state.json current so `rensei-kata status` can observe the loop.
const STATE_PROTOCOL = `
## Loop State (keep it current)

You are part of the rensei loop — record progress so it stays observable:

    npx rensei-kata status --set <phase>           # when you START a phase (id from the table above)
    npx rensei-kata status --note "what happened"  # on meaningful gate decisions or findings

One call per phase entry is enough. Never edit .rensei/state.json by hand.
`;

function sha256(text) {
  return crypto.createHash('sha256').update(text, 'utf8').digest('hex');
}

// Drift = a generated artifact was hand-edited after the last build. The next
// build would silently destroy that work — surface it instead.
function checkDrift(targetDir) {
  const manifestFile = path.join(targetDir, '.rensei', MANIFEST_FILE);
  if (!exists(manifestFile)) return [];
  let manifest;
  try {
    manifest = JSON.parse(read(manifestFile));
  } catch (e) {
    return [];
  }
  const drift = [];
  for (const [rel, hash] of Object.entries(manifest.files || {})) {
    const file = path.join(targetDir, rel);
    if (!exists(file)) { drift.push({ file: rel, kind: 'deleted' }); continue; }
    if (sha256(read(file)) !== hash) drift.push({ file: rel, kind: 'edited' });
  }
  return drift;
}

function driftWarnings(drift) {
  return drift.map(d =>
    d.kind === 'edited'
      ? `generated file was hand-edited since the last build: ${d.file} — move the change into .rensei/ (agents/<n>/prompt.md, fragments/, graph) or it will be overwritten on the next build`
      : `generated file was deleted since the last build: ${d.file} — run \`npx rensei-kata build\` to restore it`);
}

const REFERENCE_BLURBS = {
  'decision-framework': 'Full @gate decision logic — OpenSpec levels, visual criteria, edge cases',
  'model-routing': 'Which model for which task — profiles, effort guide, cost awareness',
};

function resolveModel(config, tier, runtime) {
  const t = runtimeTable(config, 'MODELS', runtime);
  return (t && t[tier]) || tier || 'sonnet';
}

function resolveEffort(config, tier, runtime) {
  const t = runtimeTable(config, 'EFFORT', runtime);
  return (t && t[tier]) || tier || 'medium';
}

// MODELS/EFFORT may be flat (one table for every runtime) or nested per
// runtime ({claude:{...}, codex:{...}}). Resolve to ONE runtime's table.
function runtimeTable(config, key, runtime) {
  const raw = config && config[key];
  if (!raw || typeof raw !== 'object') return raw;
  const values = Object.values(raw);
  const nested = values.length > 0 && values.every(v => v && typeof v === 'object');
  if (!nested) return raw;
  return raw[runtime] || raw.claude || values[0];
}

const RUNTIME_OF_TARGET = { claude: 'claude', opencode: 'opencode', codex: 'codex', all: null };

// ---------------------------------------------------------------------------
// agents
// ---------------------------------------------------------------------------

function agentLoopRows(agentName, graph, config, runtime) {
  const rows = [];
  for (const [nodeName, node] of Object.entries(graph.nodes)) {
    // terminal nodes may retain phase data (studio keeps it non-destructively) —
    // it is inert: a terminal is never an agent assignment
    if (node.terminal || nodeName !== agentName) continue;
    const incoming = (graph.edges || []).filter(e => e.to === nodeName && e.when);
    const condition = incoming.map(e => e.when).join(' OR ') || '—';
    rows.push(`| ${node.label || nodeName} | ${resolveModel(config, node.model, runtime)} | ${resolveEffort(config, node.effort, runtime)} | ${condition} |`);
  }
  return rows;
}

// Skills an agent may load, per phase: node-level override wins over agent default.
// All optional — the agent loads them only when the task calls for it.
function agentSkillRows(agentName, def, graph, config) {
  const registry = config.SKILLS || {};
  const rows = [];
  const seen = new Set();
  for (const [nodeName, node] of Object.entries(graph.nodes)) {
    if (node.terminal || nodeName !== agentName) continue;
    const skills = node.skills !== undefined ? node.skills : (def.skills || []);
    for (const s of skills) {
      const key = `${nodeName}:${s}`;
      if (seen.has(key)) continue;
      seen.add(key);
      rows.push(`| ${node.label || nodeName} | \`${s}\` | ${registry[s] || '—'} |`);
    }
  }
  // standalone use: agent defaults not bound to any phase
  const bound = new Set();
  for (const [nodeName, node] of Object.entries(graph.nodes)) {
    if (!node.terminal && nodeName === agentName) (node.skills !== undefined ? node.skills : def.skills || []).forEach(s => bound.add(s));
  }
  for (const s of def.skills || []) {
    if (!bound.has(s) && !seen.has(`standalone:${s}`)) {
      rows.push(`| standalone | \`${s}\` | ${registry[s] || '—'} |`);
    }
  }
  return rows;
}

function compileAgent(name, { def, prompt }, core, opts = {}) {
  const target = opts.target || 'claude';
  const runtime = opts.runtime || RUNTIME_OF_TARGET[target] || core.config.RUNTIME || 'claude';
  const { graph, config, fragments } = core;
  const lines = [];
  lines.push('---');
  lines.push(`name: ${name}`);
  if (target === 'opencode' || target === 'codex') {
    lines.push('mode: subagent');
    lines.push(`description: ${def.description} Use: ${def.alias}.`);
    lines.push(`model: ${resolveModel(config, def.model, runtime)}`);
    if (def.tools && def.tools.length) lines.push(`tools: [${def.tools.map(t => String(t).toLowerCase()).join(', ')}]`);
  } else {
    lines.push(`description: ${def.description} Use: ${def.alias}.`);
    lines.push(`model: ${resolveModel(config, def.model, runtime)}`);
    if (def.tools && def.tools.length) lines.push(`tools: [${def.tools.join(', ')}]`);
  }
  lines.push('---');
  lines.push(GENERATED_HEADER);
  // behavior knobs: config declares intents, compilation derives the prompt
  // fragment agents actually read (a {{BEHAVIOR.commit_step}} in a prompt
  // resolves to the full instruction line)
  const ask = !(config.BEHAVIOR && config.BEHAVIOR.ask_before_commit === false);
  const scope = {
    ...config,
    BEHAVIOR: {
      ...(config.BEHAVIOR || {}),
      commit_step: ask
        ? 'ASK before committing — "Ready to commit? [y/n]"; only commit if confirmed, otherwise leave changes uncommitted for review'
        : 'commit directly, no confirmation needed',
    },
  };
  lines.push(interpolate(prompt.trim(), scope));

  const rows = agentLoopRows(name, graph, config, runtime);
  if (rows.length) {
    lines.push('\n## Loop Assignment (from rensei.graph.yaml)\n');
    lines.push('| Phase | Model | Effort | Entry condition |');
    lines.push('|-------|-------|--------|-----------------|');
    lines.push(...rows);
    lines.push(STATE_PROTOCOL);
  }

  const skillRows = agentSkillRows(name, def, graph, config);
  if (skillRows.length) {
    lines.push('\n## Skills (optional — configurable via the graph)\n');
    lines.push('Load a skill ONLY when the task calls for its purpose. This list is data-driven:');
    lines.push('it changes when `.rensei/rensei.graph.yaml` (per-phase `skills:`) or the agent definition changes.\n');
    lines.push('| Phase | Skill | Purpose |');
    lines.push('|-------|-------|---------|');
    lines.push(...skillRows);
  }

  for (const frag of def.fragments || []) {
    if (fragments.has(frag)) {
      lines.push('\n---\n');
      lines.push(fragments.get(frag).trim());
    }
  }
  return lines.join('\n') + '\n';
}

// ---------------------------------------------------------------------------
// /kata command — generated from agent trigger data
// ---------------------------------------------------------------------------

function triggerSection(name, def, suffix, triggers) {
  const lines = [];
  lines.push(`### → @${name}${suffix}`);
  if (def[`_route_${suffix}`]) lines.push(def[`_route_${suffix}`]);
  lines.push('');
  lines.push(`**Spanish triggers:**`);
  lines.push((triggers.es || []).map(t => `"${t}"`).join(', ') || '—');
  lines.push('');
  lines.push(`**English triggers:**`);
  lines.push((triggers.en || []).map(t => `"${t}"`).join(', ') || '—');
  lines.push('');
  return lines;
}

const ROUTE_BLURBS = {
  'gate': 'Route here when the user is asking for an **evaluation, decision, or triage**. They want to know what path to take, not to execute anything yet.',
  'analyze': 'Route here when the user wants to **understand requirements deeply** — clarifying questions, detecting ambiguity, exploring edge cases. NOT asking for a plan yet.',
  'plan': 'Route here when the user wants a **concrete implementation plan** — tasks, file paths, code structure, estimates.',
  'implement': 'Route here when the user wants **code written** — implementation, creation. They want working code as output.',
  'self-critique': 'Route here when the user wants work **critiqued by its own author** — find the flaws before anyone else does.',
  'spec-review': 'Route here when the question is **"does this match the spec?"** — compliance checking against requirements or plan.',
  'quality': 'Route here when the user wants **code reviewed** — quality check, PR review. They want feedback, not changes.',
  'correct': 'Route here when the user wants **a bug fixed or review findings applied** — repair work with a clear input list.',
  'integrate': 'Route here when the user wants work **finished and merge-ready** — full suite, clean history, PR.',
  'sentinel': 'Route here when the user asks about **security** — vulnerabilities, best practices, sensitive data, auth, cryptography.',
  'designer': 'Route here when the user wants **visual design** — screens, UI, mockups, layouts. They want something that looks good.',
};

function compileKata(core) {
  const { agents, graph } = core;
  const out = [];
  // kata routes within the USER's workflow: only agents bound to graph nodes
  // are primary targets; on_demand helpers appear as a suggestions footnote
  const inGraph = new Set();
  for (const [id, node] of Object.entries(graph.nodes || {})) {
    if (!node.terminal) inGraph.add(id);
  }
  const loopAgents = [...agents].filter(([name]) => inGraph.has(name));
  const onDemand = [...agents].filter(([name, { def }]) => !inGraph.has(name) && def && def.on_demand);
  out.push(GENERATED_HEADER);
  out.push(`You are the kata (型) dispatcher for rensei (錬成). Your job is to read what the user needs — in Spanish OR English — and route it to the correct agent automatically.

## How it works

1. Read the user's request carefully
2. Match it against the trigger patterns below
3. Invoke the correct agent
4. The user does NOT need to know which agent to use or even that agents exist

## Agent Selection Guide — with detailed trigger patterns
`);

  for (const [name, { def }] of loopAgents) {
    if (def.modes) {
      for (const [mode, m] of Object.entries(def.modes)) {
        const suffix = ` (${mode} mode)`;
        const sec = triggerSection(name, def, suffix, m.triggers || {});
        const blurb = ROUTE_BLURBS[`${name}${suffix}`];
        sec.splice(1, 0, blurb || '', '');
        out.push(...sec);
      }
    } else {
      const hasTriggers = def.triggers && ((def.triggers.es || []).length || (def.triggers.en || []).length);
      if (!hasTriggers) continue;
      const sec = triggerSection(name, def, '', def.triggers);
      const blurb = ROUTE_BLURBS[name];
      sec.splice(1, 0, blurb || '', '');
      out.push(...sec);
    }
  }

  out.push(`### → Load /rensei (full loop)
Route here when the user wants **end-to-end development** — the complete loop from evaluation to integration.

**Spanish triggers:**
"full loop", "completo", "de principio a fin", "feature completa", "end to end", "todo el proceso", "hazlo todo", "ciclo completo", "desde cero", "full pipeline"

**English triggers:**
"full loop", "complete", "end to end", "full feature", "the whole thing", "do it all", "full cycle", "from scratch", "full pipeline", "entire workflow"

${onDemand.length ? `## On-demand helpers (outside the loop)

These agents are NOT phases of the loop — suggest them as an EXTRA step when the request clearly calls for it, never as the primary route:
${onDemand.map(([name, { def }]) => `- **@${name}** — ${def.description}`).join('\n')}
` : ''}
## Tie-breaking rules

1. If the request mentions BOTH analysis and planning → @analyze first (it feeds @plan)
2. If bug + review requested → @correct first, then suggest @quality after
3. If unsure between @gate and any phase agent → @gate (safer to evaluate first)
4. If code AND design mentioned → @designer first, then suggest the next loop phase
5. If truly ambiguous → @gate (it evaluates and recommends the path)
6. Security-sensitive keywords (auth, payment, token, PII, password) in ANY context → flag to also consider @sentinel

## Output format

\`\`\`
→ @{agent}

[one sentence explaining why]

[invoke the agent with the user's request]
\`\`\`

## The request

$ARGUMENTS
`);
  return out.join('\n');
}

// ---------------------------------------------------------------------------
// /rensei command + RENSEI.md — generated from the graph
// ---------------------------------------------------------------------------

function flowChain(graph) {
  // Main path from entry, following first-visit edges (ignores back edges).
  const labels = n => (graph.nodes[n] && (graph.nodes[n].label || n)) || n;
  const chain = [];
  const visited = new Set();
  let current = graph.entry;
  while (current && !visited.has(current)) {
    visited.add(current);
    chain.push(labels(current));
    const next = (graph.edges || []).find(e => e.from === current && !visited.has(e.to));
    current = next && next.to;
  }
  return chain;
}

// ---------------------------------------------------------------------------
// /rensei command — the loop RUNNER. Compiled from the graph: the phase
// program (agents, entry conditions, loop bounds) becomes an execution
// protocol the session follows, updating .rensei/state.json as it advances.
// ---------------------------------------------------------------------------

// The user-facing execution program: entry → phases with their gates.
function runProgram(graph, config) {
  const L = [];
  const label = n => (graph.nodes[n] && (graph.nodes[n].label || n)) || n;
  L.push(`entry: @${graph.entry} — every loop starts here (skip-rules below may shorten the path)`);

  // group: normal path + bounded loops, straight from the edges
  for (const e of graph.edges || []) {
    if (!e.when) continue;
    const max = e.max !== undefined ? ` (bounded: max ${resolveVar(e.max, config)}× — after that, STOP and surface it)` : '';
    const bounded = e.max !== undefined;
    L.push(bounded
      ? `loop: @${e.from} → @${e.to} when: ${e.when}${max}`
      : `advance: @${e.from} → @${e.to} when: ${e.when}`);
  }
  return L;
}

function compileRenseiCommand(core) {
  const { graph, agents, config } = core;
  const roster = [...agents.keys()].map(a => `@${a}`).join(', ');
  const program = runProgram(graph, config).map(l => `- ${l}`).join('\n');
  const skips = (graph['skip-rules'] || []).map(s => `- ${s.when} → path: ${s.path.join(' → ')}`).join('\n');
  return `${GENERATED_HEADER}
Run the rensei (錬成) loop on a task. You are the orchestrator: the graph below is
your PROGRAM — follow it phase by phase, honoring every gate.

## Boot (do this first, in order)
1. Read .rensei/RENSEI.md (config, flow, quality gates) — it is compiled from the same graph.
2. Start the loop state: \`npx rensei-kata status --start "$ARGUMENTS"\`
3. Acknowledge: "loop armed. ${agents.size} agents ready. Entry: @${graph.entry}."

## The program (from rensei.graph.yaml — the single source of truth)
${program}
${skips ? `\n### Skip rules (gate may shorten the path)\n${skips}\n` : ''}
## Execution protocol — follow exactly
1. **Enter a phase:** invoke the agent for the current phase with the accumulated
   context. FIRST action of every phase entry: \`npx rensei-kata status --set <phase-id>\`
2. **Honor the gates:** a transition only happens when its \`when:\` condition is
   genuinely met. Do not advance on hope. If a gate needs a decision only the
   user can make, ASK — do not guess.
3. **Respect the bounds:** a bounded transition that reached its max is a STOP
   condition. Surface the failure honestly; never loop silently.
4. **Carry the context:** each phase receives the previous phase's output
   (assessment → analysis → plan → …). Never re-ask what a previous phase settled.
5. **User checkpoints stay:** when a phase's own protocol says to ask (commits,
   destructive actions), it asks. The loop orchestrates; it does not steamroll.
6. **Record decisions:** \`npx rensei-kata status --note "…"\` on meaningful gate
   decisions (level chosen, spec PASS/FAIL, issues found, rework iteration #).
7. **Finish:** on entering the terminal node, \`npx rensei-kata status --note "loop complete"\`
   and hand the user the integration summary.

## If the task is trivial
The entry phase decides. If the assessment says the full path is overkill, follow
a skip rule (if one matches) or run the shortest honest path — and say which
phases you skipped and why.

$ARGUMENTS
`;
}

function compileRenseiDoc(core, runtime) {
  const { graph, config, agents } = core;
  const rt = runtime || config.RUNTIME || 'claude';
  const modelsTable = runtimeTable(config, 'MODELS', rt) || {};
  const effortTable = runtimeTable(config, 'EFFORT', rt) || {};
  const L = [];
  L.push(GENERATED_HEADER);
  L.push(`# rensei — Iterative AI Development Framework

> **rensei (錬成):** Refinamiento mediante repetición. Forjar, templar, corregir, repetir — hasta que el resultado sea excelente.
>
> **Source of truth:** \`.rensei/rensei.graph.yaml\`. This file is GENERATED — edit the graph/config and run \`npx rensei-kata build\`.

---

## Configuration

\`\`\`yaml
RUNTIME: ${rt}

MODELS (${rt}):
${Object.entries(modelsTable).map(([k, v]) => `  ${k}: ${v}`).join('\n')}

EFFORT (${rt}):
${Object.entries(effortTable).map(([k, v]) => `  ${k}: ${v}`).join('\n')}

ITERATIONS:
${Object.entries(config.ITERATIONS || {}).map(([k, v]) => `  ${k}: ${v}`).join('\n')}

SDD_TOOL: ${config.SDD_TOOL}
DESIGN_TOOL: ${config.DESIGN_TOOL}
\`\`\`

---

## The Flow

\`\`\`
${flowChain(graph).join(' → ')}
                    └────────── correction loop (max ${resolveVar('$ITERATIONS.correction_loop', config)}×): QUALITY → CORRECT → SELF-CRITIQUE ──────────┘
\`\`\`

---

## The Agents

| Agent | Alias | Loop phases | Model | Standalone |
|-------|-------|-------------|-------|------------|`);

  for (const [name, { def }] of agents) {
    const phases = Object.entries(graph.nodes)
      .filter(([n]) => !graph.nodes[n].terminal && n === name)
      .map(([pn, n]) => n.label || pn)
      .join(', ') || 'on-demand';
    L.push(`| **@${name}** | \`${def.alias}\` | ${phases} | ${resolveModel(config, def.model, runtime)} | \`${def.standalone || '—'}\` |`);
  }

  L.push(`
---

## Phase Table (from the graph)

| Phase | Agent | Model | Effort | Enters when |
|-------|-------|-------|--------|-------------|`);
  for (const [nodeName, node] of Object.entries(graph.nodes)) {
    if (node.terminal) continue;
    const incoming = (graph.edges || []).filter(e => e.to === nodeName && e.when).map(e => e.when).join(' OR ') || '—';
    L.push(`| ${node.label || nodeName} | @${nodeName} | ${resolveModel(config, node.model, runtime)} | ${resolveEffort(config, node.effort, runtime)} | ${incoming} |`);
  }

  L.push(`
---

## Quality Gates (from the graph)

| Transition | Condition |`);
  for (const e of graph.edges || []) {
    if (!e.when) continue;
    const max = e.max !== undefined ? ` (max ${resolveVar(e.max, config)}×)` : '';
    L.push(`| ${e.from} → ${e.to} | ${e.when}${max} |`);
  }

  L.push(`
---

## Skills Registry (optional, configurable)

Skills are declared here and assigned per agent (\`agents/<name>/agent.yaml\`) or per phase (\`nodes.<phase>.skills\` in the graph — editable in \`npx rensei-kata studio\`). Agents load them only when the task calls for it.

| Skill | Purpose | Used by |
|-------|---------|---------|`);
  const registry = config.SKILLS || {};
  for (const [skill, purpose] of Object.entries(registry)) {
    const users = [];
    for (const [agentName, { def }] of agents) {
      const agentDefault = (def.skills || []).includes(skill);
      const nodeUse = Object.values(graph.nodes).some(n => n.agent === agentName && (n.skills || []).includes(skill));
      if (agentDefault || nodeUse) users.push(`@${agentName}`);
    }
    L.push(`| \`${skill}\` | ${purpose} | ${users.join(', ') || '—'} |`);
  }

  L.push(`
## Reference Docs

| Doc | What's in it |
|-----|--------------|`);
  for (const filename of core.reference.keys()) {
    const slug = filename.replace(/\.md$/, '');
    L.push(`| [reference/${filename}](reference/${filename}) | ${REFERENCE_BLURBS[slug] || '—'} |`);
  }

  L.push(`
## Prompt Templates

Tool-agnostic templates in \`.rensei/prompts/\` — usable with any runtime (Claude Code print mode, OpenCode, CI):

${[...core.prompts.keys()].map(f => `- \`prompts/${f}\``).join('\n')}
`);

  L.push(`
---

## Anti-Patterns

- ❌ Skip self-critique ("the reviewer will catch it")
- ❌ Implement without a plan
- ❌ Use deep_reasoning for routine CRUD
- ❌ Use routine for architectural decisions
- ❌ Skip gate evaluation (guess instead of decide)
- ❌ Generate designs without DESIGN.md as source of truth
- ❌ "Close enough" — if it's not right, it's wrong
`);
  return L.join('\n');
}

// ---------------------------------------------------------------------------
// CLAUDE.md managed block
// ---------------------------------------------------------------------------

const BLOCK_START = '<!-- rensei-kata:start -->';
const BLOCK_END = '<!-- rensei-kata:end -->';

function updateClaudeMd(targetDir, importPath) {
  const file = path.join(targetDir, 'CLAUDE.md');
  const block = `${BLOCK_START}
<!-- Managed by rensei-kata. Edit .rensei/ and run \`npx rensei-kata build\`. -->
@${importPath}
${BLOCK_END}`;

  if (!exists(file)) {
    write(file, `# Project\n\n${block}\n`);
    return 'created';
  }
  const content = read(file);
  const re = new RegExp(`${BLOCK_START.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}[\\s\\S]*?${BLOCK_END.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}`);
  if (re.test(content)) {
    write(file, content.replace(re, block));
    return 'updated';
  }
  write(file, `${content.trimEnd()}\n\n${block}\n`);
  return 'appended';
}

// OpenCode/Codex agents read AGENTS.md (same managed-block mechanic as CLAUDE.md).
function updateAgentsMd(targetDir, importPath, target = 'opencode') {
  const file = path.join(targetDir, 'AGENTS.md');
  const block = `${BLOCK_START}
<!-- Managed by rensei-kata. Edit .rensei/ and run \`npx rensei-kata build --target ${target}\`. -->
@${importPath}
${BLOCK_END}`;

  if (!exists(file)) {
    write(file, `# Agents\n\n${block}\n`);
    return 'created';
  }
  const content = read(file);
  const re = new RegExp(`${BLOCK_START.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}[\\s\\S]*?${BLOCK_END.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}`);
  if (re.test(content)) {
    write(file, content.replace(re, block));
    return 'updated';
  }
  write(file, `${content.trimEnd()}\n\n${block}\n`);
  return 'appended';
}

// ---------------------------------------------------------------------------
// main compile
// ---------------------------------------------------------------------------

function compile(core, targetDir, { global: isGlobal = false, target = 'claude', runtime = null } = {}) {
  const written = [];
  const targets = target === 'all' ? ['claude', 'opencode'] : [target];
  const renseiDir = path.join(targetDir, '.rensei');
  const manifest = { version: 1, target, files: {} };
  const track = (abs) => {
    const rel = toPosix(path.relative(targetDir, abs));
    manifest.files[rel] = sha256(read(abs));
  };

  // The graph is the source of truth: only nodes in it are compiled. Agents
  // lingering in .rensei/agents/ after a node was deleted (or renamed away)
  // are GHOSTS — they must not reach the runtime. on_demand helpers are the
  // only exception (sentinel: outside the loop, invocable standalone).
  const fs = require('fs');
  const graphAgents = new Set();
  for (const [id, node] of Object.entries(core.graph.nodes || {})) {
    if (!node.terminal) graphAgents.add(id);
  }
  const onDemand = new Set();
  for (const [name, { def }] of core.agents) {
    if (def && def.on_demand) onDemand.add(name);
  }
  const liveAgents = new Map();
  for (const [name, agent] of core.agents) {
    if (graphAgents.has(name) || onDemand.has(name)) liveAgents.set(name, agent);
  }
  const ghosts = [];
  for (const [name, agent] of core.agents) {
    if (!liveAgents.has(name)) ghosts.push({ name, agent });
  }
  const purged = [];

  for (const t of targets) {
    // claude → .claude/{agents,commands,rules} · opencode → .opencode/{agents,commands,rule}
    // (opencode uses PLURAL for agents/commands, singular for rule — per its docs)
    const isOpen = t === 'opencode' || t === 'codex';
    const base = isOpen ? path.join(targetDir, '.opencode') : path.join(targetDir, '.claude');
    const agentsDir = isOpen ? path.join(base, 'agents') : path.join(base, 'agents');
    const commandsDir = isOpen ? path.join(base, 'commands') : path.join(base, 'commands');
    const rulesDir = isOpen ? path.join(base, 'rule') : path.join(base, 'rules');
    const rt = runtime || RUNTIME_OF_TARGET[t] || core.config.RUNTIME || 'claude';

    // 1. agents — graph-scoped; ghosts are REMOVED from the runtime dirs so
    //    deleted agents stop existing everywhere at once
    for (const [name, agent] of liveAgents) {
      const file = path.join(agentsDir, `${name}.md`);
      write(file, compileAgent(name, agent, core, { target: t, runtime: rt }));
      written.push(file);
    }
    for (const g of ghosts) {
      for (const ghost of [path.join(agentsDir, `${g.name}.md`), path.join(agentsDir, `${g.name}.yaml`)]) {
        if (exists(ghost)) { fs.rmSync(ghost); purged.push(toPosix(path.relative(targetDir, ghost))); }
      }
    }

    // 2. commands — with a description frontmatter (both runtimes show it in
    //    their slash-command pickers)
    const kataFile = path.join(commandsDir, 'kata.md');
    write(kataFile, `---\ndescription: Dispatch a request to the right rensei agent (ES/EN) — no agent roster knowledge needed\n---\n${compileKata(core)}`);
    written.push(kataFile);

    const renseiCmdFile = path.join(commandsDir, 'rensei.md');
    write(renseiCmdFile, `---\ndescription: Run the rensei loop on a task — graph-compiled execution protocol (phases, gates, bounds)\n---\n${compileRenseiCommand(core)}`);
    written.push(renseiCmdFile);

    // 3. rules
    for (const [filename, content] of core.rules) {
      const file = path.join(rulesDir, filename);
      write(file, content);
      written.push(file);
    }

    // 4. entry-point managed block: CLAUDE.md (claude) / AGENTS.md (opencode/codex)
    const importPath = isGlobal
      ? toPosix(path.join(targetDir, '.rensei', 'RENSEI.md'))
      : '.rensei/RENSEI.md';
    if (isOpen) updateAgentsMd(targetDir, importPath, t);
    else updateClaudeMd(targetDir, importPath);
  }

  // 5. compiled methodology doc + diagram live next to the graph (target-shared)
  const docFile = path.join(renseiDir, 'RENSEI.md');
  write(docFile, compileRenseiDoc(core, runtime));
  written.push(docFile);

  const diagramFile = path.join(renseiDir, 'graph.html');
  write(diagramFile, renderDiagram(core));
  written.push(diagramFile);

  // 6. framework-managed reference docs + prompt templates (overwrite is safe:
  //    these are not user data — user edits belong in graph/config/agents)
  for (const [filename, content] of core.reference) {
    const file = path.join(renseiDir, 'reference', filename);
    write(file, content);
    written.push(file);
  }
  for (const [filename, content] of core.prompts) {
    const file = path.join(renseiDir, 'prompts', filename);
    write(file, content);
    written.push(file);
  }

  // 7. build manifest — lets validate/doctor detect hand-edited artifacts
  for (const f of written) track(f);
  const manifestFile = path.join(renseiDir, MANIFEST_FILE);
  write(manifestFile, JSON.stringify(manifest, null, 2) + '\n');
  written.push(manifestFile);

  const mdActions = [];
  if (targets.includes('claude')) mdActions.push('CLAUDE.md updated (managed block)');
  if (targets.some(t => t === 'opencode' || t === 'codex')) mdActions.push('AGENTS.md updated (managed block)');
  const out = { written, claudeMdAction: mdActions.join(' · ') };
  if (purged.length) out.purged = purged;
  if (ghosts.length) out.ghostsInRensei = ghosts.map(g => g.name); // .rensei/agents/ dirs kept (user data)
  return out;
}

module.exports = { compile, compileAgent, compileKata, compileRenseiDoc, flowChain, checkDrift, driftWarnings };
